server:
  port: 8761

spring:
  application:
    name: itsop-eureka-server
  zipkin:
    base-url: http://localhost:9200
  boot:
    admin:
      client:
        url: http://localhost:8084

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 3000

