server:
  port: 8761

eureka:
  client:
    #是否从eureka上获取注册信息
    fetch-registry: false
    #表示是否注册自身到eureka服务器
    register-with-eureka: false
    serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
  server:  #配置属性，但由于 Eureka 自我保护模式以及心跳周期长的原因，经常会遇到 Eureka Server 不剔除已关停的节点的问题
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000 #清理无效节点的时间间隔，默认60秒

