server:
  port: 8084

spring:
  application:
    name: itsop-boot-admin-server
  main:
    allow-bean-definition-overriding: true
  zipkin:
    base-url: http://localhost:9411

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/