server:
  port: 9200

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.101:3306/auction?characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
  application:
    name: itsop-user-server
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084
  redis:
    # Redis服务器地址
    host: 192.168.0.101
    # Redis服务器连接端口
    port: 16379
    timeout: 2000ms

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

mybatis-plus:
  type-aliases-package: com.clouds.zh.itsop.common.module.user
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    #开启SQL打印 开发环境打开，生产环境关闭
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
  row-bounds-with-count: true
  helper-dialect: mysql
