server:
  port: 9200

spring:
  application:
    name: itsop-user-server
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
