server:
  port: 9411

spring:
  application:
    name: itsop-zipkin-server
  #解决 The bean 'characterEncodingFilter', defined in class path resource [zipkin/autoconfigure/ui/ZipkinUiAutoConfiguration.class], could not be registered.
  main:
    allow-bean-definition-overriding: true
  boot:
    admin:
      client:
        url: http://localhost:8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false