server:
  port: 4082

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    #开发数据库
#    url: jdbc:oracle:thin:@10.0.14.206:1521/SCMDEV
#    username: sisdev
#    password: Sisdev_20190107
    
    #测试数据库
    url: jdbc:oracle:thin:@10.0.14.197:1521/SCMTEST
    username: sistest
    password: Sistest_20190107
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      StatViewServlet:
        #监控页面地址 登录用户名 密码
        urlPatterns: /druid/*
        loginUsername: admin
        loginPassword: sany123456
        #IP白名单(没有配置或者为空，则允许所有访问)
        #allow: 192.168.1.62
        #IP黑名单 (存在共同时，deny优先于allow)
        #deny: 192.168.1.113
        #禁用HTML页面上的“Reset All”功能
        #resetEnable: false
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
    zipkin:
      base-url: http://localhost:9411/ # 指定了 Zipkin 服务器的地址

mybatis-plus:
  typeAliasesPackage: com.sany.model
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID" 5, "字符串全局唯一ID";
    id-type: 5
  #开启驼峰
  configuration:
    map-underscore-to-camel-case: true
    #开启SQL语句输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#刷新配置文件验证值
sis.profile: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

