
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true # 设置本客户端是否从服务注册中心获取服务 默认true
    serviceUrl:
      defaultZone: http:/${eureka.instance.name}:${eureka.instance.password}/@${eureka.instance.hostname}:${eureka-server-port}/eureka/
    eureka-server-port: 8671
  instance:
    lease-renewal-interval-in-seconds: 5 # 设置注册的服务多久向服务注册中心发送心跳包(单位s)
    lease-expiration-duration-in-seconds: 20
    prefer-ip-address: true
    hostname: 192.168.0.107
    name: itsop
    password: itsop123
